<template>
  <div class="inspection-page">
    <div class="page-heading">
      <div><h2>巡检管理</h2><p>管理巡检点位与现场任务指派</p></div>
      <el-button type="primary" @click="openPointDialog">新增点位</el-button>
    </div>
    <el-tabs v-model="activeTab" class="inspection-tabs">
      <el-tab-pane label="任务总览" name="tasks">
        <div class="toolbar"><el-select v-model="taskStatus" clearable placeholder="任务状态" @change="loadTasks"><el-option label="待处理" value="待处理"/><el-option label="执行中" value="执行中"/><el-option label="已完成" value="已完成"/><el-option label="漏检" value="漏检"/></el-select><el-button @click="loadTasks">刷新</el-button></div>
        <el-table :data="tasks" border><el-table-column prop="name" label="任务名称" min-width="190"/><el-table-column prop="point" label="巡检点位" width="170"/><el-table-column prop="assignee" label="责任人" width="120"/><el-table-column prop="deadline" label="截止时间" width="170"/><el-table-column label="状态" width="110"><template #default="s"><el-tag :type="taskTag(s.row.status)">{{s.row.status}}</el-tag></template></el-table-column><el-table-column label="操作" width="180" fixed="right"><template #default="s"><el-button link type="primary" @click="openAssign(s.row)">{{s.row.assignee ? '转派' : '指派'}}</el-button><el-button link @click="viewTask(s.row)">查看</el-button></template></el-table-column></el-table>
      </el-tab-pane>
      <el-tab-pane label="点位管理" name="points">
        <div class="toolbar"><el-input v-model="pointKeyword" clearable placeholder="搜索点位名称/编号" style="width:260px"/><el-button type="primary" @click="openPointDialog">新增点位</el-button><el-button @click="batchQr">批量生成二维码</el-button></div>
        <el-table :data="filteredPoints" border><el-table-column prop="code" label="点位编号" width="150"/><el-table-column prop="name" label="点位名称" min-width="180"/><el-table-column prop="type" label="类型" width="130"/><el-table-column prop="area" label="区域" width="130"/><el-table-column prop="floor" label="楼层" width="120"/><el-table-column label="状态" width="100"><template #default="s"><el-tag :type="s.row.enabled ? 'success' : 'info'">{{s.row.enabled ? '启用' : '停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="s"><el-button link type="primary" @click="editPoint(s.row)">编辑</el-button><el-button link @click="togglePoint(s.row)">{{s.row.enabled ? '停用' : '启用'}}</el-button></template></el-table-column></el-table>
      </el-tab-pane>
      <el-tab-pane label="任务计划" name="plans"><div class="toolbar"><el-button type="primary" @click="createPlan">新建计划</el-button></div><el-table :data="plans" border><el-table-column prop="name" label="计划名称"/><el-table-column prop="cycle" label="周期" width="110"/><el-table-column prop="shift" label="班次" width="150"/><el-table-column prop="owner" label="责任人" width="120"/><el-table-column prop="status" label="状态" width="100"><template #default="s"><el-tag type="success">{{s.row.status}}</el-tag></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane label="检查模板" name="templates"><el-table :data="templates" border><el-table-column prop="name" label="模板名称"/><el-table-column prop="items" label="检查项" width="100"/><el-table-column prop="method" label="检查方法"/><el-table-column label="操作" width="120"><template #default="s"><el-button link type="primary" @click="editTemplate(s.row)">编辑检查项</el-button></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane label="执行记录" name="records"><el-table :data="records" border><el-table-column prop="code" label="巡检编号"/><el-table-column prop="person" label="巡检人员"/><el-table-column prop="route" label="巡检路线"/><el-table-column prop="status" label="任务状态"/><el-table-column prop="abnormal" label="异常项"/></el-table></el-tab-pane>
      <el-tab-pane label="异常工单" name="exceptions"><el-table :data="exceptions" border><el-table-column prop="code" label="异常编号"/><el-table-column prop="point" label="点位"/><el-table-column prop="description" label="异常描述"/><el-table-column prop="status" label="闭环状态"><template #default="s"><el-tag type="warning">{{s.row.status}}</el-tag></template></el-table-column><el-table-column label="操作" width="100"><template #default="s"><el-button link type="primary" @click="closeException(s.row)">关闭</el-button></template></el-table-column></el-table></el-tab-pane>
    </el-tabs>

    <el-dialog v-model="pointVisible" :title="pointForm.code ? '编辑点位' : '新增点位'" width="520px" append-to-body>
      <el-form :model="pointForm" label-width="90px"><el-form-item label="点位名称"><el-input v-model="pointForm.name" placeholder="如：1#配电柜"/></el-form-item><el-form-item label="点位类型"><el-input v-model="pointForm.type" placeholder="如：配电房/消防"/></el-form-item><el-form-item label="所属区域"><el-input v-model="pointForm.area"/></el-form-item><el-form-item label="楼层位置"><el-input v-model="pointForm.floor"/></el-form-item></el-form>
      <template #footer><el-button @click="pointVisible=false">取消</el-button><el-button type="primary" @click="savePoint">保存</el-button></template>
    </el-dialog>
    <el-dialog v-model="assignVisible" title="指派巡检任务" width="460px" append-to-body><el-form label-width="90px"><el-form-item label="任务名称">{{ assignTask?.name }}</el-form-item><el-form-item label="责任人"><el-select v-model="assignName" placeholder="选择员工" style="width:100%"><el-option v-for="worker in workers" :key="worker.employeeId" :label="worker.nickname || worker.username" :value="worker.nickname || worker.username"/></el-select></el-form-item></el-form><template #footer><el-button @click="assignVisible=false">取消</el-button><el-button type="primary" @click="saveAssign">确认指派</el-button></template></el-dialog>
    <el-dialog v-model="templateVisible" :title="`${activeTemplate?.name || ''} · 检查项`" width="760px" append-to-body><el-table :data="activeTemplate?.checks || []" border><el-table-column type="index" label="#" width="60"/><el-table-column prop="name" label="检查项目"/><el-table-column prop="method" label="检查方法"/><el-table-column label="结果选项"><template #default="s"><el-tag v-for="v in s.row.options" :key="v" effect="plain" class="option-tag">{{v}}</el-tag></template></el-table-column><el-table-column label="必填" width="80"><template #default="s"><el-tag type="success">是</el-tag></template></el-table-column></el-table></el-dialog>
  </div>
</template>
<script setup>
import { computed, ref } from 'vue'; import { ElMessage } from 'element-plus'; import request from '@/api/request.js'
const activeTab=ref('tasks'), taskStatus=ref(''), pointKeyword=ref(''), pointVisible=ref(false), assignVisible=ref(false), assignTask=ref(null), assignName=ref(''), templateVisible=ref(false), activeTemplate=ref(null)
const workers=ref([]); const pointForm=ref({code:'',name:'',type:'',area:'',floor:''})
const points=ref([{code:'P-2026-001',name:'1#配电柜',type:'配电房',area:'教学区',floor:'B-1F',enabled:true},{code:'P-2026-002',name:'消防栓-3栋',type:'消防',area:'宿舍区',floor:'3栋1F',enabled:true},{code:'P-2026-003',name:'生活水泵',type:'水泵房',area:'后勤区',floor:'-1F',enabled:true}])
const tasks=ref([{name:'配电房日间巡检',point:'1#配电柜',assignee:'李强',deadline:'今日 10:00',status:'已完成'},{name:'消防栓巡检',point:'消防栓-3栋',assignee:'王磊',deadline:'今日 14:00',status:'执行中'},{name:'泵房设备检查',point:'生活水泵',assignee:'',deadline:'今日 16:00',status:'漏检'}])
const checks=(names)=>names.map((name,i)=>({name,method:i%2?'目视':'目视+仪表',options:['正常','异常','不适用']})); const plans=ref([{name:'配电房日间巡检',cycle:'每日',shift:'早班 08:00-12:00',owner:'李强',status:'启用'},{name:'宿舍消防周检',cycle:'每周一',shift:'中班',owner:'王磊',status:'启用'}]); const templates=ref([{name:'配电房巡检',items:10,method:'目视、仪表、听觉',checks:checks(['环境温度','环境湿度','异常声响','异常气味','电压表读数','电流表读数','开关状态','指示灯状态','柜体清洁','安全标识'])},{name:'水泵房巡检',items:8,method:'目视+听觉',checks:checks(['水泵运行状态','进出水压力','管道阀门','控制柜指示灯','环境温度','环境湿度','消防泵状态','周边环境'])},{name:'空调/新风巡检',items:6,method:'目视、温度计',checks:checks(['运行状态','温度设定','滤网状态','冷凝水排放','控制面板','周边环境'])}]); const records=ref([{code:'R-20260820-01',person:'李强',route:'配电房日间巡检',status:'已完成',abnormal:0},{code:'R-20260820-02',person:'王磊',route:'消防栓周检',status:'异常完成',abnormal:2}]); const exceptions=ref([{code:'EX-20260820-01',point:'消防栓-3栋',description:'压力表读数异常',status:'待处理'}])
const filteredPoints=computed(()=>points.value.filter(p=>!pointKeyword.value || `${p.code}${p.name}`.includes(pointKeyword.value)))
const taskTag=s=>s==='已完成'?'success':s==='漏检'?'danger':s==='执行中'?'warning':'info'
const loadTasks=()=>{ if(taskStatus.value) tasks.value=tasks.value.filter(t=>t.status===taskStatus.value); }
const openPointDialog=()=>{pointForm.value={code:'',name:'',type:'',area:'',floor:''};pointVisible.value=true}; const editPoint=p=>{pointForm.value={...p};pointVisible.value=true}
const savePoint=()=>{if(!pointForm.value.name)return ElMessage.warning('请填写点位名称'); if(!pointForm.value.code)pointForm.value.code=`P-${Date.now()}`; const i=points.value.findIndex(p=>p.code===pointForm.value.code); i>-1?points.value.splice(i,1,{...pointForm.value}):points.value.push({...pointForm.value,enabled:true});pointVisible.value=false;ElMessage.success('点位已保存')}
const togglePoint=p=>{p.enabled=!p.enabled}; const batchQr=()=>ElMessage.info('二维码批量生成入口已准备，可接入打印服务'); const viewTask=t=>ElMessage.info(`任务：${t.name}`)
const openAssign=async t=>{assignTask.value=t;assignName.value=t.assignee||'';try{const r=await request.get('/employee/selectAll');workers.value=r.data||[]}catch{workers.value=[]}assignVisible.value=true}; const saveAssign=()=>{if(!assignName.value)return ElMessage.warning('请选择责任人');assignTask.value.assignee=assignName.value;assignTask.value.status='待处理';assignVisible.value=false;ElMessage.success('任务已指派')}
const createPlan=()=>ElMessage.info('计划创建入口已准备'); const editTemplate=t=>{activeTemplate.value=t;templateVisible.value=true}; const closeException=e=>{e.status='已关闭';ElMessage.success('异常已关闭')}
</script>
<style scoped>
.inspection-page{padding:4px}.page-heading{display:flex;align-items:center;justify-content:space-between;margin-bottom:20px}.page-heading h2{margin:0;color:#172033;font-size:22px}.page-heading p{margin:6px 0 0;color:#8290a5;font-size:13px}.inspection-tabs{background:#fff;border:1px solid #e7edf5;border-radius:12px;padding:0 20px 20px}.toolbar{display:flex;gap:10px;align-items:center;margin:16px 0}.option-tag{margin-right:6px}
</style>
